// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package db

import (
	"context"
)

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT code, name, created_at
FROM countries
WHERE code = $1
`

func (q *Queries) GetCountryByCode(ctx context.Context, code string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByCode, code)
	var i Country
	err := row.Scan(&i.Code, &i.Name, &i.CreatedAt)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT code, name, created_at
FROM countries
ORDER BY name ASC
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.Code, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
