// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eta_rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createETARule = `-- name: CreateETARule :one
INSERT INTO eta_rules (
    nationality_code,
    destination_code,
    eta_required,
    effective_from,
    effective_to,
    source_name,
    source_url
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, nationality_code, destination_code, eta_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
`

type CreateETARuleParams struct {
	NationalityCode string
	DestinationCode string
	EtaRequired     bool
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	SourceName      string
	SourceUrl       string
}

func (q *Queries) CreateETARule(ctx context.Context, arg CreateETARuleParams) (EtaRule, error) {
	row := q.db.QueryRow(ctx, createETARule,
		arg.NationalityCode,
		arg.DestinationCode,
		arg.EtaRequired,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.SourceName,
		arg.SourceUrl,
	)
	var i EtaRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.EtaRequired,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteETARule = `-- name: DeleteETARule :exec
DELETE FROM eta_rules
WHERE id = $1
`

func (q *Queries) DeleteETARule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteETARule, id)
	return err
}

const findETARule = `-- name: FindETARule :one
SELECT id, nationality_code, destination_code, eta_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM eta_rules
WHERE nationality_code = $1
  AND destination_code = $2
  AND effective_from <= $3
  AND (
      effective_to IS NULL
      OR effective_to >= $3
  )
ORDER BY effective_from DESC
LIMIT 1
`

type FindETARuleParams struct {
	NationalityCode string
	DestinationCode string
	EffectiveFrom   pgtype.Date
}

func (q *Queries) FindETARule(ctx context.Context, arg FindETARuleParams) (EtaRule, error) {
	row := q.db.QueryRow(ctx, findETARule, arg.NationalityCode, arg.DestinationCode, arg.EffectiveFrom)
	var i EtaRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.EtaRequired,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getETARuleByID = `-- name: GetETARuleByID :one
SELECT id, nationality_code, destination_code, eta_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM eta_rules
WHERE id = $1
`

func (q *Queries) GetETARuleByID(ctx context.Context, id pgtype.UUID) (EtaRule, error) {
	row := q.db.QueryRow(ctx, getETARuleByID, id)
	var i EtaRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.EtaRequired,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listETARules = `-- name: ListETARules :many
SELECT id, nationality_code, destination_code, eta_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM eta_rules
ORDER BY nationality_code, destination_code, effective_from
`

func (q *Queries) ListETARules(ctx context.Context) ([]EtaRule, error) {
	rows, err := q.db.Query(ctx, listETARules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EtaRule
	for rows.Next() {
		var i EtaRule
		if err := rows.Scan(
			&i.ID,
			&i.NationalityCode,
			&i.DestinationCode,
			&i.EtaRequired,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.SourceName,
			&i.SourceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
