// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Country struct {
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type EtaRule struct {
	ID              pgtype.UUID
	NationalityCode string
	DestinationCode string
	EtaRequired     bool
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	SourceName      string
	SourceUrl       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Passport struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	NationalityCode string
	ExpiresAt       pgtype.Date
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type StayRule struct {
	ID              pgtype.UUID
	NationalityCode string
	DestinationCode string
	MaxStayDays     int32
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	SourceName      string
	SourceUrl       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Trip struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	PassportID      pgtype.UUID
	DestinationCode string
	DepartureDate   pgtype.Date
	ReturnDate      pgtype.Date
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type VisaRule struct {
	ID              pgtype.UUID
	NationalityCode string
	DestinationCode string
	VisaRequired    bool
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	SourceName      string
	SourceUrl       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
