// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPassport = `-- name: CreatePassport :one
INSERT INTO passports (
    user_id,
    nationality_code,
    expires_at
)
VALUES ($1, $2, $3)
RETURNING id, user_id, nationality_code, expires_at, created_at, updated_at
`

type CreatePassportParams struct {
	UserID          pgtype.UUID
	NationalityCode string
	ExpiresAt       pgtype.Date
}

func (q *Queries) CreatePassport(ctx context.Context, arg CreatePassportParams) (Passport, error) {
	row := q.db.QueryRow(ctx, createPassport, arg.UserID, arg.NationalityCode, arg.ExpiresAt)
	var i Passport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NationalityCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePassport = `-- name: DeletePassport :exec
DELETE FROM passports
WHERE id = $1
`

func (q *Queries) DeletePassport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePassport, id)
	return err
}

const getPassportByID = `-- name: GetPassportByID :one
SELECT id, user_id, nationality_code, expires_at, created_at, updated_at
FROM passports
WHERE id = $1
`

func (q *Queries) GetPassportByID(ctx context.Context, id pgtype.UUID) (Passport, error) {
	row := q.db.QueryRow(ctx, getPassportByID, id)
	var i Passport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NationalityCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPassportsByUserID = `-- name: ListPassportsByUserID :many
SELECT id, user_id, nationality_code, expires_at, created_at, updated_at
FROM passports
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPassportsByUserID(ctx context.Context, userID pgtype.UUID) ([]Passport, error) {
	rows, err := q.db.Query(ctx, listPassportsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passport
	for rows.Next() {
		var i Passport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NationalityCode,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassport = `-- name: UpdatePassport :one
UPDATE passports
SET
    nationality_code = $2,
    expires_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, nationality_code, expires_at, created_at, updated_at
`

type UpdatePassportParams struct {
	ID              pgtype.UUID
	NationalityCode string
	ExpiresAt       pgtype.Date
}

func (q *Queries) UpdatePassport(ctx context.Context, arg UpdatePassportParams) (Passport, error) {
	row := q.db.QueryRow(ctx, updatePassport, arg.ID, arg.NationalityCode, arg.ExpiresAt)
	var i Passport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NationalityCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
