// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stay_rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStayRule = `-- name: CreateStayRule :one
INSERT INTO stay_rules (
    nationality_code,
    destination_code,
    max_stay_days,
    effective_from,
    effective_to,
    source_name,
    source_url
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, nationality_code, destination_code, max_stay_days, effective_from, effective_to, source_name, source_url, created_at, updated_at
`

type CreateStayRuleParams struct {
	NationalityCode string
	DestinationCode string
	MaxStayDays     int32
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	SourceName      string
	SourceUrl       string
}

func (q *Queries) CreateStayRule(ctx context.Context, arg CreateStayRuleParams) (StayRule, error) {
	row := q.db.QueryRow(ctx, createStayRule,
		arg.NationalityCode,
		arg.DestinationCode,
		arg.MaxStayDays,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.SourceName,
		arg.SourceUrl,
	)
	var i StayRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.MaxStayDays,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStayRule = `-- name: DeleteStayRule :exec
DELETE FROM stay_rules
WHERE id = $1
`

func (q *Queries) DeleteStayRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStayRule, id)
	return err
}

const findStayRule = `-- name: FindStayRule :one
SELECT id, nationality_code, destination_code, max_stay_days, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM stay_rules
WHERE nationality_code = $1
  AND destination_code = $2
  AND effective_from <= $3
  AND (
      effective_to IS NULL
      OR effective_to >= $3
  )
ORDER BY effective_from DESC
LIMIT 1
`

type FindStayRuleParams struct {
	NationalityCode string
	DestinationCode string
	EffectiveFrom   pgtype.Date
}

func (q *Queries) FindStayRule(ctx context.Context, arg FindStayRuleParams) (StayRule, error) {
	row := q.db.QueryRow(ctx, findStayRule, arg.NationalityCode, arg.DestinationCode, arg.EffectiveFrom)
	var i StayRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.MaxStayDays,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStayRuleByID = `-- name: GetStayRuleByID :one
SELECT id, nationality_code, destination_code, max_stay_days, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM stay_rules
WHERE id = $1
`

func (q *Queries) GetStayRuleByID(ctx context.Context, id pgtype.UUID) (StayRule, error) {
	row := q.db.QueryRow(ctx, getStayRuleByID, id)
	var i StayRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.MaxStayDays,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStayRules = `-- name: ListStayRules :many
SELECT id, nationality_code, destination_code, max_stay_days, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM stay_rules
ORDER BY nationality_code, destination_code, effective_from
`

func (q *Queries) ListStayRules(ctx context.Context) ([]StayRule, error) {
	rows, err := q.db.Query(ctx, listStayRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StayRule
	for rows.Next() {
		var i StayRule
		if err := rows.Scan(
			&i.ID,
			&i.NationalityCode,
			&i.DestinationCode,
			&i.MaxStayDays,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.SourceName,
			&i.SourceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
