// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    user_id,
    passport_id,
    destination_code,
    departure_date,
    return_date
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, passport_id, destination_code, departure_date, return_date, created_at, updated_at
`

type CreateTripParams struct {
	UserID          pgtype.UUID
	PassportID      pgtype.UUID
	DestinationCode string
	DepartureDate   pgtype.Date
	ReturnDate      pgtype.Date
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserID,
		arg.PassportID,
		arg.DestinationCode,
		arg.DepartureDate,
		arg.ReturnDate,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PassportID,
		&i.DestinationCode,
		&i.DepartureDate,
		&i.ReturnDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips
WHERE id = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrip, id)
	return err
}

const getTripByID = `-- name: GetTripByID :one
SELECT id, user_id, passport_id, destination_code, departure_date, return_date, created_at, updated_at
FROM trips
WHERE id = $1
`

func (q *Queries) GetTripByID(ctx context.Context, id pgtype.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PassportID,
		&i.DestinationCode,
		&i.DepartureDate,
		&i.ReturnDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTripsByPassportID = `-- name: ListTripsByPassportID :many
SELECT id, user_id, passport_id, destination_code, departure_date, return_date, created_at, updated_at
FROM trips
WHERE passport_id = $1
ORDER BY departure_date ASC, created_at DESC
`

func (q *Queries) ListTripsByPassportID(ctx context.Context, passportID pgtype.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByPassportID, passportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PassportID,
			&i.DestinationCode,
			&i.DepartureDate,
			&i.ReturnDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByUserID = `-- name: ListTripsByUserID :many
SELECT id, user_id, passport_id, destination_code, departure_date, return_date, created_at, updated_at
FROM trips
WHERE user_id = $1
ORDER BY departure_date ASC, created_at DESC
`

func (q *Queries) ListTripsByUserID(ctx context.Context, userID pgtype.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PassportID,
			&i.DestinationCode,
			&i.DepartureDate,
			&i.ReturnDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET
    passport_id = $2,
    destination_code = $3,
    departure_date = $4,
    return_date = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, passport_id, destination_code, departure_date, return_date, created_at, updated_at
`

type UpdateTripParams struct {
	ID              pgtype.UUID
	PassportID      pgtype.UUID
	DestinationCode string
	DepartureDate   pgtype.Date
	ReturnDate      pgtype.Date
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.ID,
		arg.PassportID,
		arg.DestinationCode,
		arg.DepartureDate,
		arg.ReturnDate,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PassportID,
		&i.DestinationCode,
		&i.DepartureDate,
		&i.ReturnDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
