// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visa_rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisaRule = `-- name: CreateVisaRule :one
INSERT INTO visa_rules (
    nationality_code,
    destination_code,
    visa_required,
    effective_from,
    effective_to,
    source_name,
    source_url
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, nationality_code, destination_code, visa_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
`

type CreateVisaRuleParams struct {
	NationalityCode string
	DestinationCode string
	VisaRequired    bool
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	SourceName      string
	SourceUrl       string
}

func (q *Queries) CreateVisaRule(ctx context.Context, arg CreateVisaRuleParams) (VisaRule, error) {
	row := q.db.QueryRow(ctx, createVisaRule,
		arg.NationalityCode,
		arg.DestinationCode,
		arg.VisaRequired,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.SourceName,
		arg.SourceUrl,
	)
	var i VisaRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.VisaRequired,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVisaRule = `-- name: DeleteVisaRule :exec
DELETE FROM visa_rules
WHERE id = $1
`

func (q *Queries) DeleteVisaRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVisaRule, id)
	return err
}

const findVisaRule = `-- name: FindVisaRule :one
SELECT id, nationality_code, destination_code, visa_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM visa_rules
WHERE nationality_code = $1
  AND destination_code = $2
  AND effective_from <= $3
  AND (
    effective_to IS NULL
    OR effective_to >= $3
  )
ORDER BY effective_from DESC
LIMIT 1
`

type FindVisaRuleParams struct {
	NationalityCode string
	DestinationCode string
	EffectiveFrom   pgtype.Date
}

func (q *Queries) FindVisaRule(ctx context.Context, arg FindVisaRuleParams) (VisaRule, error) {
	row := q.db.QueryRow(ctx, findVisaRule, arg.NationalityCode, arg.DestinationCode, arg.EffectiveFrom)
	var i VisaRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.VisaRequired,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisaRuleByID = `-- name: GetVisaRuleByID :one
SELECT id, nationality_code, destination_code, visa_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM visa_rules
WHERE id = $1
`

func (q *Queries) GetVisaRuleByID(ctx context.Context, id pgtype.UUID) (VisaRule, error) {
	row := q.db.QueryRow(ctx, getVisaRuleByID, id)
	var i VisaRule
	err := row.Scan(
		&i.ID,
		&i.NationalityCode,
		&i.DestinationCode,
		&i.VisaRequired,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceName,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVisaRules = `-- name: ListVisaRules :many
SELECT id, nationality_code, destination_code, visa_required, effective_from, effective_to, source_name, source_url, created_at, updated_at
FROM visa_rules
ORDER BY nationality_code, destination_code, effective_from
`

func (q *Queries) ListVisaRules(ctx context.Context) ([]VisaRule, error) {
	rows, err := q.db.Query(ctx, listVisaRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisaRule
	for rows.Next() {
		var i VisaRule
		if err := rows.Scan(
			&i.ID,
			&i.NationalityCode,
			&i.DestinationCode,
			&i.VisaRequired,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.SourceName,
			&i.SourceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
